# 服务端口
server:
  port: 8003
spring:
  application:
    # 服务名
    name: service-vod
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI5tKKTAQVaCoFzJwN6the
      keysecret: 8xuMGC9YLXCLeadvGiHEaNh8BSnjvA


