# 服务端口
server:
  port: 8160

# 服务名
spring:
  application:
    name: service-ucenter
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolcloud?serverTimezone=GMT%2B8
    password: 11235813
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: 1
mybatis-plus:
  mapper-locations: classpath:com/wddlhyss/eduservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
