#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tKKTAQVaCoFzJwN6the
      keysecret: 8xuMGC9YLXCLeadvGiHEaNh8BSnjvA
      bucketname: schoolofcloud



